name: Generate Snake Animation

on:
  schedule:
    # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the Snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          # Your GitHub username
          github_user_name: 07jhashubham
          # Path to the generated SVG file
          outputs: dist/output/github-contribution-grid-snake.svg

      # Push the changes
      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
